version: "3.9"
services:
  web:
    build: .
    ports:
      - "8000:8000"
    environment:
      DB_URL: "redis://default:123@redis:6379/0"
  redis:
    image: redis:6.2.5-alpine
    ports:
      - "6379:6379"